version: '3'
services:
  nginx:
    image: nginx:1.15.2-alpine-perl
    build: ./docker/nginx/
    ports:
      - "443:443"
      - "8443:8443"
      - "9443:9443"
    depends_on:
      - php
    volumes:
      - ./cert:/usr/local/nginx/conf
      - ./html:/var/www/html
      - ./conf/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/nginx/fcgi_params:/etc/nginx/fcgi_params
      - ./log/nginx:/var/log/nginx
    dns:
      - 8.8.8.8
    networks:
      - backend
  
  h2o:
    image: lkwg82/h2o-http2-server:latest
    ports:
      - "1443:1443"
    depends_on:
      - php
    volumes:
      - ./html:/var/www/html
      - ./log/h2o:/var/log/h2o
      - ./conf/h2o/h2o.conf:/etc/h2o/h2o.conf
      - ./cert:/etc/h2o/cert
    networks:
      - backend
  
  apache:
    image: httpd:2.4.34-alpine
    build: ./docker/apache/
    ports:
      - "2443:443"
    depends_on:
      - php
    volumes:
      - ./cert/server.key:/usr/local/apache2/conf/server.key
      - ./cert/server.crt:/usr/local/apache2/conf/server.crt
      - ./conf/apache2/my-httpd.conf:/usr/local/apache2/conf/my-httpd.conf
      - ./html:/usr/local/apache2/htdocs
    networks:
      - backend

  php:
    image: php:7-fpm-alpine
    build: ./docker/php/
    volumes:
      - ./html:/var/www/html
    tty: true
    networks:
      - backend

networks:
  backend:
